# -*- coding: utf-8 -*-
"""Cópia de WoMakersCode Bootcamp Data Analytics (2025.1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvWI69uVkCweJ0wQ21PcGFILC8Q79cmC

DESAFIO 1

Crie um programa que solicita ao usuário que insira três notas (valores de 0 a 10) e, em seguida, calcule e exiba a média dessas notas.

Além disso, informe ao usuário se ele foi aprovado ou reprovado com base na média das notas, considerando a média mínima de aprovação como 6.
"""

#Execute seu código aqui

#Função para calcular a média de três notas

def calcular_media(nota1, nota2, nota3):
  return (nota1 + nota2 + nota3) / 3

# Função para verificar se foi aprovado ou reprovado
def verificar_aprovacao(media):
  if media >= 6:
    return "Passou"
  else:
    return "Não passou"

# Solicita as três notas do usuário
nota1 = float(input("Insira a primeira nota (0 a 10): "))
nota2 = float(input("Insira a segunda nota (0 a 10): "))
nota3 = float(input("Insira a terceira nota (0 a 10): "))

# Calcula a média
media = calcular_media(nota1, nota2, nota3)

# Exibe a média e o resultado
print(f"\nMédia: {media:.2f}")
print(f"Resultado: {verificar_aprovacao(media)}")

"""DESAFIO 2

Escreva um programa que receba uma string e conte quantas vogais (a, e, i, o, u) ela contém.
"""

#Execute seu código aqui

# Função para contar as vogais em uma string
def contar_vogais(texto):
  vogais = "aeiou"
  contador = 0
  for letra in texto:
    if letra in vogais:
      contador += 1
  return contador

# Solicita a string do usuário
texto = input("Digite uma palavra: ")

# Conta e exibe o número de vogais
quantidade_vogais = contar_vogais(texto)
print(f"A string contém {quantidade_vogais} vogais.")

"""DESAFIO 3

Escreva um programa em que o computador escolhe um número aleatório entre 1 e 100 e o usuário tenta adivinhar. O programa deve informar se o palpite é muito alto, muito baixo ou correto.
"""

#Execute seu código aqui

import random

# Função principal do jogo

def adivinhar_numero():
    numero_secreto = random.randint(1, 100)
    palpite = None
    tentativas = 0

    print("Estou pensando em um número entre 1 e 100. Tente adivinhar!")

# Loop até o palpite estar correto

    while palpite != numero_secreto:
      palpite = int(input("Digite o seu palpite: "))
      tentativas += 1

      if palpite < numero_secreto:
        print("Muito baixo! Tente novamente.")
      elif palpite > numero_secreto:
        print("Muito alto! Tente novamente.")
      else:
        print (f"Parabéns! Você acertou o número {numero_secreto} em {tentativas} tentativas.")

# Inicia o jogo
adivinhar_numero()

"""DESAFIO 4

Crie um programa que permita ao usuário gerenciar suas tarefas diárias. O programa deve oferecer as seguintes funcionalidades:

Adicionar uma nova tarefa;

Visualizar todas as tarefas;

Remover uma tarefa;

Sair do programa.

(Você pode implementar essas funcionalidades usando listas para armazenar as tarefas e estruturas de controle como loops e condicionais para interagir com o usuário.)
"""

# Função para exibir o menu
def exibir_menu():
    print("\nGerenciador de Tarefas")
    print("1. Adicionar nova tarefa")
    print("2. Visualizar todas as tarefas")
    print("3. Remover uma tarefa")
    print("4. Sair")

# Função para adicionar uma tarefa
def adicionar_tarefa(tarefas):
    tarefa = input("Digite a nova tarefa: ")
    tarefas.append(tarefa)
    print(f"Tarefa '{tarefa}' adicionada com sucesso!")

# Função para visualizar todas as tarefas
def visualizar_tarefas(tarefas):
    if len(tarefas) == 0:
        print("Nenhuma tarefa encontrada.")
    else:
        print("\nLista de Tarefas:")
        for i, tarefa in enumerate(tarefas, 1):
            print(f"{i}. {tarefa}")

# Função para remover uma tarefa
def remover_tarefa(tarefas):
    visualizar_tarefas(tarefas)
    if len(tarefas) > 0:
        try:
            indice = int(input("\nDigite o número da tarefa que deseja remover: "))
            if 1 <= indice <= len(tarefas):
                tarefa_removida = tarefas.pop(indice - 1)
                print(f"Tarefa '{tarefa_removida}' removida com sucesso!")
            else:
                print("Número inválido.")
        except ValueError:
            print("Entrada inválida, insira um número.")

# Função principal do programa
def gerenciador_tarefas():
    tarefas = []
    while True:
        exibir_menu()
        opcao = input("Escolha uma opção (1-4): ")

        if opcao == "1":
            adicionar_tarefa(tarefas)
        elif opcao == "2":
            visualizar_tarefas(tarefas)
        elif opcao == "3":
            remover_tarefa(tarefas)
        elif opcao == "4":
            print("Saindo do programa... Até logo!")
            break
        else:
            print("Opção inválida. Tente novamente.")

# Executa o gerenciador de tarefas
gerenciador_tarefas()

"""DESAFIO 5

Escreva um programa em Python que funcione como uma calculadora simples. Ele deve pedir ao usuário para inserir dois números e, em seguida, solicitar a operação que deseja realizar (adição, subtração, multiplicação ou divisão).
"""

#Execute seu código aqui

# Funções da calculadora

def adicionar(a, b):
  return a + b

def subtrair(a, b):
  return a - b

def multiplicar(a, b):
  return a * b

def dividir(a, b):
  if b == 0:
    return " A divisão por zero não é permitida."
  return a / b

# Função principal da calculadora

def calculadora():
  num1 = float(input("Ditige o primeiro número: "))
  num2 = float(input("Digite o segundo número: "))

  # Solicitação das operações desejadas
  print("\nEscolha a operação: ")
  print("1. Adição (+)")
  print("2. Subtração (-)")
  print("3. Multiplicação (*)")
  print("4. Divisão (/)")

  operacao = input("Digite a operação desejada (1/2/3/4): ")

  #Executar as operações que foram escolhidas e exibir o nosso resultado

  if operacao == '1':
    print(f"\nResultado: {num1} + {num2} = {adicionar(num1, num2)}")
  elif operacao == '2':
    print(f"\nResultado: {num1} - {num2} = {subtrair(num1, num2)}")
  elif operacao == '3':
    print(f"\nResultado: {num1} * {num2} = {multiplicar(num1, num2)}")
  elif operacao == '4':
    resultado = dividir(num1, num2)
    print(f"\nResultado: {num1} / {num2} = {resultado}")
  else:
    print("Operação inválida. Tente novamente.")

# Executar a calculadora
calculadora()